image: node:latest

stages:
  - build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/
    - packages/
    - ~/.pnpm-store

build_and_test:
  variables:
     KUBERNETES_CPU_REQUEST: 4
     KUBERNETES_CPU_LIMIT: 4
     KUBERNETES_MEMORY_REQUEST: 4Gi
     KUBERNETES_MEMORY_LIMIT: 4Gi
  stage: build
  before_script:
    - curl -L https://unpkg.com/@pnpm/self-installer | node
    - pnpm config set store-dir `pwd`/.pnpm-store
    - pnpm recursive install --frozen-lockfile=false
  script:
    - pnpm run build --if-present
    - pnpm run pretest
    - node packages/parallel_test.js
 
